version: '3'
services:
  nfvo:
    image: openbaton/nfvo:latest
    depends_on:
      - rabbitmqbroker
      - nfvodatabase
      - zabbixserver
    restart: always
    environment:
      - NFVO_RABBIT_BROKERIP=${HOST_IP} # for use in userdata.sh in vnfm-generic
      - NFVO_MONITORING_IP=${HOST_IP}
      - NFVO_QUOTA_CHECK=false
      - NFVO_PLUGIN_INSTALLATION-DIR=/dev/null
      - SPRING_RABBITMQ_HOST=rabbitmqbroker
      - SPRING_DATASOURCE_URL=jdbc:mysql://nfvodatabase:3306/openbaton
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    ports:
      - "8080:8080"

  vnfmgeneric:
    image: openbaton/vnfm-generic:latest
    depends_on:
      - nfvo
    restart: always
    environment:
      - VNFM_RABBITMQ_BROKERIP=rabbitmqbroker

  pluginvimdrivertest:
    image: openbaton/plugin-vimdriver-test:5.1.0
    depends_on:
      - nfvo
    restart: always
    environment:
      - RABBITMQ=rabbitmqbroker
  pluginvimdriveropenstack4j:

    image: openbaton/plugin-vimdriver-openstack-4j:latest
    depends_on:
      - nfvo
    restart: always
    environment:
      - RABBITMQ=rabbitmqbroker

  pluginmonitoringzabbix:
    image: openbaton/plugin-monitoring-zabbix:5.1.1
    depends_on:
      - nfvo
    restart: always
    environment:
      - ZABBIX_PLUGIN_IP=${HOST_IP}
      - FAULTS_CONSUMER_ENDPOINT=http://faultmanagementsystem:9000/alarm/vr
      - ZABBIX_HOST=zabbixwebapachemysql
      - RABBITMQ_BROKERIP=rabbitmqbroker
      - ZABBIX_ENDPOINT=/api_jsonrpc.php
      - ZABBIX_PORT=80
    ports:
      - "8010:8010"

  faultmanagementsystem:
    image: openbaton/fms:latest
    depends_on:
      - nfvo
      - pluginmonitoringzabbix
      - fmsdatabase
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmqbroker
      - NFVO_IP=nfvo
      - PLUGIN_IP=zabbix-plugin
      - SPRING_DATASOURCE_URL=jdbc:mysql://fmsdatabase:3306/faultmanagement
      - MYSQL_DATABASE=faultmanagement
      - MYSQL_USER=fmsuser
      - MYSQL_PASSWORD=Password1

  autoscalingengine:
    image: openbaton/ase:latest
    depends_on:
      - nfvo
      - pluginmonitoringzabbix
    restart: always
    environment:
      - ASE_RABBITMQ_BROKERIP=rabbitmqbroker
      - ASE_SERVER_IP=autoscalingengine
      - NFVO_IP=nfvo
      - PLUGIN_IP=zabbix-plugin

  networkslicingengine:
    image: openbaton/nse:latest
    depends_on:
      - nfvo
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmqbroker
      - NFVO_IP=nfvo

  rabbitmqbroker:
    image: rabbitmq:3-management-alpine
    restart: always
    hostname: openbaton-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=openbaton
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq

  zabbixserver:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    volumes:
      - zbxalert:/usr/lib/zabbix/alertscripts
    environment:
      - DB_SERVER_HOST=zabbixdatabase
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Password1
      - MYSQL_ROOT_PASSWORD=Password1

  zabbixwebapachemysql:
    image: zabbix/zabbix-web-apache-mysql
    depends_on:
      - zabbixdatabase
      - zabbixserver
    ports:
      - "80:80"
    environment:
      - DB_SERVER_HOST=zabbixdatabase
      - ZBX_SERVER_HOST=zabbixserver
      - MYSQL_DATABASE=zabbix
      - PHP_TZ=Europe/Rome
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Password1
      - MYSQL_ROOT_PASSWORD=Password1

  nfvodatabase:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=openbaton
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=changeme
    volumes:
      - dbdata_nfvo:/var/lib/mysql
  fmsdatabase:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=faultmanagement
      - MYSQL_USER=fmsuser
      - MYSQL_PASSWORD=changeme
    volumes:
      - dbdata_fms:/var/lib/mysql

  zabbixdatabase:
    image: mysql:5.7
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Password1
      - MYSQL_ROOT_PASSWORD=Password1
    volumes:
      - dbdata_zabbix:/var/lib/mysql

  k8sharbor:
    build: ./
    restart: always
    depends_on:
      - nfvo
    environment:
      - RABBITMQ=rabbitmqbroker
      - HARBOR_ADDRESS=127.0.0.1

volumes:
  rabbitdata:
  zbxalert:
  dbdata_fms:
  dbdata_nfvo:
  dbdata_zabbix: